config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :credits
    resources :requests
  end
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :credits, only: [:index, :show]
  resources :requests
  resources :users
  root :to => 'visitors#index'
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %li= link_to 'Edit account', edit_user_registration_path
  %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  %li= link_to 'Sign in', new_user_session_path
  %li= link_to 'Sign up', new_user_registration_path
- if user_signed_in?
  - if current_user.try(:admin?)
    %li= link_to 'Admin', '/admin'
    %li= link_to 'Users', users_path

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'

    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          - if user_signed_in? && (current_user.admin? || current_user.manager?)
            = link_to "Administrate", admin_credits_path
          - elsif user_signed_in?
            = link_to "My Account", "/pages/profile"
        %li
          = link_to "About", "/pages/about"
        %li
          = link_to "Credits", credits_path
        %li
          = link_to "Contact", "/pages/contact"
        %li
          - if user_signed_in?
            = link_to "Log out", destroy_user_session_path
          -  else
            = link_to "Log in", new_user_session_path
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "EasyCredit"
    %meta{:content => "#{content_for?(:description) ? yield(:description) : "EasyCredit"}", :name => "description"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    / Custom Fonts
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic", :rel => "stylesheet", :type => "text/css"}/
  %body
    %header
      = render 'layouts/navigation' unless current_page?(root_path)
    %br
    %br
    = render 'layouts/messages'
    = yield